# frozen_string_literal: true
require 'solidus_add_purchase_policies_to_admin_panel/configuration'
require 'solidus_add_purchase_policies_to_admin_panel/version'
require 'solidus_add_purchase_policies_to_admin_panel/engine'
